### ISSUE TITLE
Maven repo doesn't contain source artifacts

### ISSUE THREAD

**Issue by reckart** [openminted/omtd-registry-api#1]
There are no source artifacts for the module in https://repo.openminted.eu/content/repositories/releases

**Comment by courado** [comment]
A bit more definition on this one ?
You mean version 1.1.1 ?

**Comment by reckart** [comment]
The repo listed above only contains a POM and a JAR file at

https://repo.openminted.eu/content/repositories/releases/eu/openminted/omtd-registry-api/1.1.0/

Normally, during a release process, also at least the SOURCES-JAR should be deployed to the repo. Cf.

http://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.9/

Having the SOURCES-JAR in the repo is convenient as can IDEs automatically download the SOURCES-JAR when opening a class from the JAR which allows seeing the source code and debugging more efficiently.

See also this post on stackoverflow:

https://stackoverflow.com/questions/4713374/maven-release-plugin-deployment-of-sources-jar-and-javadoc-jar
