### ISSUE TITLE
Changing the default branch of this repo to "develop" in the repo settings?

### ISSUE THREAD

**Issue by reckart** [openminted/omtd-registry-api#4]
How about changing the default branch of this repo to "develop" in the repo settings?

**Comment by courado** [comment]
I'm not the owner, but the main branch of a git project should be the master branch and not the snapshot versions.

**Comment by reckart** [comment]
From the respective help text in the GitHub repo settings:

> The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.

I assume that any commits and pull requests should go against the "develop" branch, right?

**Comment by courado** [comment]
You assume correct.
The default branch means nothing in particular aside from what is shown when you first click the repo.
A single `git checkout develop` is very simple.

**Comment by reckart** [comment]
Sure. But when I first come to the repo, I expect (and the docu seems to hint at that as well) that the code that I see is the latest code, i.e. the develop branch - not old code, i.e. the last release. That is why I had opened #3. If the default branch had been "develop", it would have been clear from the start that there was already code for OMTD-SHARE 2.0.0.

**Comment by courado** [comment]
I would expect the front page of a repo to be something stable I can use and from one day to another it wouldn't suddenly have setters in random classes.

Again this is not important since the default branch means nothing in the end, and if you want to change please feel free, it wont break anything.
