### ISSUE TITLE
Unable to set several fields of PersonInfo

### ISSUE THREAD

**Issue by reckart** [openminted/omtd-registry-api#5]
PersonInfo has only getters but no setters for the following fields:

* surnames
* givenNames
* names

@pennyl67 might be interesting for you as well.

**Comment by courado** [comment]
From the docs : 
```
  /**
   * Gets the value of the names property.
   * 
   * <p>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the names property.
   * 
   * <p>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getNames().add(newItem);
   * </pre>
   * 
   * 
   * <p>
   * Objects of the following type(s) are allowed in the list
   * {@link Names }
   * 
   * 
   */
```

Click here to see the [jenkins build](https://builds.openminted.eu/view/omtd/job/omtd-registry-api/ws/target/generated-sources/xjc/eu/openminted/registry/domain/PersonInfo.java/*view*/)

**Comment by reckart** [comment]
Uh ok... that seems as bit ugly and not matching the Java bean conventions... but ok.

**Comment by reckart** [comment]
Why does `IdentificationInfo` have set methods for list-type properties then? E.g.

```
    public void setResourceShortNames(List<ResourceShortName> resourceShortNames) {
        this.resourceShortNames = resourceShortNames;
    }
```
